# Generated by Django 5.2.7 on 2025-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_type', models.CharField(choices=[('mental_health', 'মানসিক স্বাস্থ্য সহায়তা'), ('physical_health', 'শারীরিক স্বাস্থ্য সমস্যা'), ('emergency', 'জরুরী সাহায্য প্রয়োজন'), ('other', 'অন্যান্য')], max_length=20)),
                ('description', models.TextField()),
                ('contact_preference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('clinic', 'কমিউনিটি ক্লিনিক'), ('hospital', 'হাসপাতাল'), ('pharmacy', 'ফার্মেসি'), ('chw', 'কমিউনিটি স্বাস্থ্যকর্মী')], max_length=20)),
                ('address', models.TextField()),
                ('upazila', models.CharField(max_length=100)),
                ('union', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('hours', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', '😊 খুব ভালো'), ('neutral', '😐 ঠিক আছে'), ('sad', '😔 কিছুটা খারাপ'), ('anxious', '😰 চিন্তিত'), ('angry', '😠 রাগান্বিত')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
