# Generated by Django 5.2.7 on 2025-11-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('health_camp', 'স্বাস্থ্য ক্যাম্প'), ('vaccination', 'টিকাদান কর্মসূচী'), ('screening', 'স্বাস্থ্য স্ক্রীনিং'), ('awareness', 'সচেতনতা সেশন'), ('blood_donation', 'রক্তদান শিবির')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.TextField()),
                ('upazila', models.CharField(max_length=100)),
                ('union', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('bcg', 'BCG (যক্ষ্মা)'), ('opv0', 'OPV-0 (পোলিও)'), ('penta1', 'Penta-1 (পেন্টাভ্যালেন্ট)'), ('penta2', 'Penta-2 (পেন্টাভ্যালেন্ট)'), ('penta3', 'Penta-3 (পেন্টাভ্যালেন্ট)'), ('mr1', 'MR-1 (হাম ও রুবেলা)'), ('mr2', 'MR-2 (হাম ও রুবেলা)')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.childvaccination')),
            ],
        ),
    ]
