# Generated by Django 5.2.7 on 2025-11-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_childvaccination_healthevent_pregnancytracker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp_available', models.BooleanField(default=False)),
                ('village', models.CharField(max_length=100)),
                ('union', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=200)),
                ('training_organization', models.CharField(max_length=200)),
                ('available_hours', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('languages', models.CharField(default='বাংলা', max_length=100)),
            ],
        ),
    ]
